version: "3.9"
services:
  bid-the-sip-db:
    image: postgres
    restart: always
    container_name: bid-the-sip-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      PDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
